### ISSUE TITLE
Unite supervisor agent under one subgraph

### ISSUE THREAD

**Issue by Teneroy** [kyma-project/kyma-companion#170]
### Description
Currently our planner, "supervisor agent"(TaskExecutor), and finalizer are separate nodes of a graph. We want to unite everything with the same subgraph called "Supervisor Agent", since our supervisor agent is a combination of those nodes.

### Acceptance criterias:

- [x] All nodes are united under the same subgraph

### Diagram 

![Image](https://github.com/user-attachments/assets/eecba9d1-688b-49ac-9d1a-eb08aa3df399)

**Comment by marcobebway** [comment]
TODOs:
- [ ] Make sure the finalizer has the following information in its prompt:
  - [ ] The user query.
  - [ ] The list of agents.

**Comment by grischperl** [comment]
Documentation PR: https://github.tools.sap/kyma/ai-force/pull/232
