### ISSUE TITLE
Make blackbox test job to get triggered manually instead of automatically

### ISSUE THREAD

**Issue by Teneroy** [kyma-project/kyma-companion#177]
Since our blackbox test is getting triggered automatically, we consume unnecessary tokens  for our testing because most of the changes do not directly affect companion performance. Therefore, we need to switch from automatic trigger of the test to manual. 

Acceptance criteria:

- [ ] Test is triggered manually and not automatically

**Comment by friedrichwilken** [comment]
Test get's triggered when the label `evaluation requested` get's added to a PR. A comment will left to any PR that informs about this behavior.
