### ISSUE TITLE
Reduce Parallelization of Queries to AI Companion in Testing Framework

### ISSUE THREAD

**Issue by Teneroy** [kyma-project/kyma-companion#196]
## Description

The goal of this task is to reduce the level of parallelization when querying the AI Companion in our testing framework. Currently, all test cases are processed and queried in parallel, which causes us to consistently hit the rate limits of AI-Core during test execution. We need to adjust the framework to process test cases in batches of 1-2, where each batch is executed in parallel, and then proceed to the next batch once the previous one is completed.

## Subtasks

1. **Analyze Current Parallelization Logic:**
   - Review the existing implementation where all test cases are queried in parallel.
   - Identify the points where queries are dispatched and processed simultaneously.

2. **Implement Batch Processing:**
   - Modify the querying mechanism to process test cases in batches of 1-2.
   - Ensure that each batch runs in parallel, but the next batch only starts after the previous batch is fully processed.

3. **Testing and Validation:**
   - Test the updated framework with the new batch processing mechanism to ensure it processes test cases correctly.
   - Verify that the rate limit is no longer hit during test execution with the new configuration. If it hits still, reduce parallelization even more
   - Ensure that there are no regressions in the accuracy or functionality of the testing framework after this change.

## Acceptance Criteria

- The testing framework queries the AI Companion in batches of 1-2 test cases at a time.
- No rate limits are hit during the test execution process.
- The overall functionality and accuracy of the tests are maintained.
- The updated framework is thoroughly tested, and batch processing works smoothly across all test cases.

**Comment by grischperl** [comment]
1 worker:
   - no rate limiting
   - time taken: 16m 21s, 16m 11s, 16m 10s

**Comment by grischperl** [comment]
2 workers:
   - rate limiting occurs
   - time taken: 10m 4s (failed due to rate limiting), 10m 52s(failed due to rate limiting)
