### ISSUE TITLE
Read model configurations dynamically at runtime

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma-companion#197]
**Description**

Currently we use the [config.yml](https://github.com/kyma-project/kyma-companion/blob/main/config/config.yml) file to read the model configurations. We need to come up with another approach to read these configurations at runtime.

**Reason(s)**

- Remove configuration hardcoding.
- Support for loading dynamic configurations at runtime.
- Support for the containerization of the Companion backend.
- Support for the secret rotation at runtime (even if it is achieved by restarting the Companion deployment).

**Acceptance Criteria**
TBD

[**Results from research and team agreements**](https://github.com/kyma-project/kyma-companion/issues/197#issuecomment-2435098329)

**Comment by friedrichwilken** [comment]
## Considerations
`gen-ai-hub` needs either
	- A: env vars
	- B: a json file, that is located at `~/.aicore/config.json`, which can be changed via the env. var `AICORE_HOME`

## Team agreement
> - Have one file for running the app that contains all the configurations.
> - Load config from file, set env vars for [`gen-ai-hub doc`](https://pypi.org/project/generative-ai-hub-sdk/) from config file via code.
> - When deploying to k8s, mount secret with all settings as config file.
> - Have the config in the json format for easy reading.
> - Watch changes in that file and restart app if accordingly.
