### ISSUE TITLE
Develop Initial Version of Kyma Agent

### ISSUE THREAD

**Issue by Teneroy** [kyma-project/kyma-companion#214]
## Description

The goal of this task is to develop the initial version of the **Kyma agent**, which will be responsible for processing tasks related to **Kyma Runtime** and its resources. The agent will be equipped with tools to retrieve Kyma-specific resources from the Kubernetes cluster and will be integrated with existing **RAG tools** for documentation retrieval. The Kyma agent will work as part of the Kyma Companion system, ensuring that Kyma-related tasks are handled effectively. This task also involves building the tool for resource retrieval from the cluster and connecting the RAG tools already developed to the agent. Testing and validation of these functionalities will be performed to ensure the agent operates smoothly.

## Tasks

1. **Develop the Kyma Agent:**
   - Implement the initial version of the **Kyma agent**, which will be responsible for processing tasks related to **Kyma Runtime** and its resources.
   - Ensure the agent has the ability to handle multiple types of requests and tasks related to Kyma resources.

2. **Implement Tool to Retrieve Kyma Resources from the Cluster:**
   - Develop a tool within the Kyma agent that retrieves **Kyma resources** from the Kubernetes cluster.
   - Ensure the tool is capable of accessing and gathering necessary runtime resource data.

3. **Connect Existing RAG Tools to the Kyma Agent:**
   - Integrate the **RAG (Retrieval-Augmented Generation) tools** into the Kyma agent for retrieving Kyma documentation.
   - Ensure seamless integration between the RAG tools and the Kyma agent’s processes.

4. **Testing and Validation:**
   - Implement tests for the Kyma agent to validate that it retrieves Kyma resources correctly and interacts with the RAG tools as expected.
   - Ensure the Kyma agent is fully functional and integrated within the Kyma Companion system.

## Acceptance Criteria

- The **Kyma agent** is developed and can handle tasks related to **Kyma Runtime** and its resources.
- A tool for **retrieving Kyma resources** from the cluster is implemented and tested.
- The **RAG tools** for documentation retrieval are connected to the Kyma agent and work as intended.
- The agent and its tools are fully tested, with successful retrieval of resources and documentation.

**Comment by Teneroy** [comment]
Consider adding a k8s resource retrieval tool as well (just a suggestion)

**Comment by muralov** [comment]
follow-ups: 
- https://github.com/kyma-project/kyma-companion/issues/268
