### ISSUE TITLE
Epic: Develop Kyma Companion Manager MVP

### ISSUE THREAD

**Issue by Teneroy** [kyma-project/kyma-companion#24]
**Description:**
Develop the MVP (Minimum Viable Product) of the Kyma Companion Manager operator, which will manage the deployments of the Kyma Companion components. The manager should facilitate the Companion Custom Resource (CR) to handle HANA Vector DB, Redis, and AI-Core secrets. Documentation should be provided on how to deploy the manager both locally and to the development cluster.

**Tasks:**

#58 
#59

**Comment by lilitgh** [comment]
https://book.kubebuilder.io/

**Comment by grischperl** [comment]
[PR #186](https://github.tools.sap/kyma/ai-force/pull/186) Documentation for Hana DB, Redis and AI-Core setup
