### ISSUE TITLE
Make Kyma Agent take into consideration documentation more often

### ISSUE THREAD

**Issue by Teneroy** [kyma-project/kyma-companion#284]
Currently when we are asking companion to write an API rule, for example, often Kyma Agent can pull the documentation, but wouldn't consider it fully. Instead, it should reply with the retrieved Kyma documentation if information available there.
Try smaller chunking that may improve it as it points to the exact documents part.

**Acceptance criteria**
* [x] Apply smaller more granular smaller chunking for indexing
* [x] Make the Kyma agent respond based on the Kyma documentation

**Comment by Teneroy** [comment]
https://cloud.langfuse.com/project/cm3udx3f8026q4kcpogyxzn8p/traces/682fdaab-dad3-4519-b146-5718c10a009e?timestamp=2024-11-26T23%3A34%3A13.355Z

**Comment by muralov** [comment]
Here is an example of agent pulling documentation, but writing an API rule with a wrong version:
![Image](https://github.com/user-attachments/assets/488e924c-e7b8-46bd-8125-1d482342a09e)

![Image](https://github.com/user-attachments/assets/504b42c5-db70-47e7-826c-cd1e81f1f00c)

**Comment by muralov** [comment]
here is the Langfuse trace: https://cloud.langfuse.com/project/cm3udx3f8026q4kcpogyxzn8p/traces/682fdaab-dad3-4519-b146-5718c10a009e?timestamp=2024-11-26T23%3A34%3A13.355Z
